from typing import Protocol


class AgentMemory(Protocol):
    async def start(self) -> None: ...

    async def search(self, query: str) -> str: ...

    async def add(self, user_message: str, assistant_message: str) -> None: ...

    async def close(self) -> None: ...
